#!/bin/bash

# Starts a Parity-hbbft node
# =========================
#
# Optional environment variables:
#
# * PARITY_LOG_ADDTL:
#
#   Appends additional logging args (debug, trace, filters, etc.).
#
# * PARITY_RELEASE:
#
#   Builds in debug mode if `PARITY_RELEASE` == `0` or `false`.
#   Slows down output and makes reading log easier.
#
#

BOOTNODE="enode://b21ad0c808eaac7af2e45b8468bb1616675cdb91ae81c8f2cf5c95761b1776a2a00b85c76c4f9adc8047bdfe58bf09d247ef07b539b7541655c0c37b81423e33@127.0.0.1:30400"

let HOST_ID=$1
let PEER_0_ID=$HOST_ID==0?$HOST_ID+2:$HOST_ID-1
let PEER_1_ID=$HOST_ID+1
let NETWORK_PORT=30400+$HOST_ID
let JSONRPC_PORT=8500+$HOST_ID
let WS_PORT=8600+$HOST_ID

printf -v HOST_HYDRABADGER_PORT "59%02d" $HOST_ID
printf -v PEER_0_HYDRABADGER_PORT "59%02d" $PEER_0_ID
printf -v PEER_1_HYDRABADGER_PORT "59%02d" $PEER_1_ID
printf -v PEER_1_HYDRABADGER_PORT "59%02d" $PEER_1_ID

if [[ $PARITY_RELEASE ]]
then
    case "$PARITY_RELEASE" in
        0|false) RELEASE=""; DIRECTORY="debug" ;;
        *) RELEASE="--release"; DIRECTORY="release" ;;
    esac
else
    RELEASE="--release"
    DIRECTORY="release"
fi

set -ex

cargo build $RELEASE || exit

# Launches node.
bash -c "\
RUST_LOG=$PARITY_LOG target/$DIRECTORY/parity \
    --chain indica \
    --base-path $HOME/.poanetwork/indica/node_$HOST_ID \
    --db-path $HOME/.poanetwork/indica/node_$HOST_ID/chains \
    --keys-path $HOME/.poanetwork/indica/node_$HOST_ID/keys \
    --port $NETWORK_PORT \
    --jsonrpc-port $JSONRPC_PORT \
    --ws-port $WS_PORT \
    --hbbft-port $HOST_HYDRABADGER_PORT \
    --hbbft-remote-addresses 127.0.0.1:5900 \
    --jsonrpc-apis web3,eth,pubsub,net,parity,private,parity_pubsub,parity_set,traces,rpc,shh,shh_pubsub,personal,parity_accounts \
    --password=node.pwds \
    --reseal-on-txs="none" \
    --usd-per-tx=0 \
	--force-sealing \
    --bootnodes=$BOOTNODE \
    $2 $3 $4 $5 $6 $7 $8 \
"
