#!/bin/bash

# Starts a parity-hhbft-indica node using the `--engine-signer` option.

# case $1 in
#     0) NODE_ACCOUNT="0x00bd138abd70e2f00903268f3db08f2d25677c9e";;
#     1) NODE_ACCOUNT="0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2";;
#     2) NODE_ACCOUNT="0x002e28950558fbede1a9675cb113f0bd20912019";;
# esac

#./indica-node $1 \
#	--engine-signer=$NODE_ACCOUNT \
#	$2 $3 $4 $5 $6 $7

# Just use the node 0 account for all
./indica-node $1 \
	--engine-signer="0x00bd138abd70e2f00903268f3db08f2d25677c9e" \
	$2 $3 $4 $5 $6 $7