#!/bin/bash

base_dir=$(git rev-parse --show-toplevel)

npm=$(type -p npm)
g_eslint=$(type -p eslint)
l_eslint=$(type -p $base_dir/js/node_modules/.bin/eslint)

# Check that `npm` and `eslint` are installed
if [ -n "$npm" ] && [ -n "$l_eslint" -o -n "$g_eslint" ]; then
	(cd $base_dir/js && npm run lint:cached)
	exit $?
fi

exit 0
