{
 "title": "OpenEthereum_1",
 "time": { "from": "2020-06-10T16:05:07.848Z", "to": "2020-06-10T16:08:24.212Z" },
 "panels": [
  {
   "title": "Highest block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "oe_sync_blocks_highest" }
   ]
  },
  {
   "title": "Earliest non pruned state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "oe_prunning_earliest_state" }
   ]
  },
  {
   "title": "Sync status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "oe_sync_status" }
   ]
  },
  {
   "title": "RPC Metrics Reponse time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "targets": [
    { "expr": "oe_metrics_time" }
   ]
  },
  {
   "title": "Block/s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(oe_import_blocks[1m])" }
   ]
  },
  {
   "title": "MGas/s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oe_import_gas[1m])/1000000"
    }
   ]
  },
  {
   "title": "Tx/s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(oe_import_txs[1m])" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "oe_net_peers" },
    { "expr": "oe_net_active_peers" }
   ]
  },
  {
   "title": "DB IO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(oe_io_bytes_read[1m])" },
    { "expr": "rate(oe_io_bytes_written[1m])" },
    {
     "expr": "rate(oe_io_cache_read_bytes[1m])/60"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "oe_queue_size_unverified" },
    { "expr": "oe_queue_size_verified" },
    { "expr": "oe_queue_size_verifying" }
   ]
  },
  {
   "title": "Pending Snapshot download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oe_snapshot_download_chunks - oe_snapshot_download_chunks_done",
     "legendFormat": "Pending blocks"
    },
    {
     "expr": "rate(oe_snapshot_download_chunks_done[5m])*3600",
     "legendFormat": "Rate per hour"
    }
   ]
  },
  {
   "title": "Snapshot restore",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "oe_snapshot_restore_block" }
   ]
  },
  {
   "title": "Snapshot GAP",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oe_chain_block - oe_chain_warpsync_gap_last"
    }
   ]
  },
  {
   "title": "Snapshot create",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "oe_snapshot_create_block" }
   ]
  },
  {
   "title": "Blockchain cache",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "oe_blockchaincache_block_details"
    },
    {
     "expr": "oe_blockchaincache_block_recipts"
    },
    { "expr": "oe_blockchaincache_blocks" },
    { "expr": "oe_blockchaincache_txaddrs" },
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "oe_queue_mem_used" },
    { "expr": "oe_sync_mem_used" },
    { "expr": "oe_statedb_mem_used" }
   ]
  }
 ]
}