// Copyright 2015-2017 Parity Technologies (UK) Ltd.
// This file is part of Parity.

// Parity is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Parity is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Parity.  If not, see <http://www.gnu.org/licenses/>.

import keycode from 'keycode';
import { observer } from 'mobx-react';
import React, { Component, PropTypes } from 'react';
import ReactDOM from 'react-dom';

import { api } from '../parity';
import DappsStore from '../dappsStore';
import Input from '../Input';
import SelectAccount from '../SelectAccount';

import styles from './dappModal.css';

@observer
export default class DappCard extends Component {
  dappsStore = DappsStore.instance();

  static propTypes = {
    dapp: PropTypes.object.isRequired,
    open: PropTypes.bool.isRequired,
    onClose: PropTypes.func.isRequired
  };

  componentWillReceiveProps (nextProps) {
    if (nextProps.open && !this.props.open) {
      this.handleOpen();
    }
  }

  render () {
    const { dapp, open } = this.props;

    const classes = [ styles.modal ];

    if (open) {
      classes.push(styles.open);
    }

    return (
      <div
        className={ classes.join(' ') }
        onClick={ open ? this.handleClose : null }
        onKeyUp={ this.handleKeyPress }
      >
        <div
          className={ styles.container }
          onClick={ open ? this.stopEvent : null }
          ref='container'
          tabIndex={ open ? 0 : null }
        >
          <div
            className={ styles.close }
            onClick={ this.handleClose }
            onKeyPress={ this.handleCloseKeyPress }
            tabIndex={ open ? 0 : null }
            title='close'
          >
            ❌
          </div>

          { this.renderHeader(dapp) }
          { this.renderContent(dapp) }
        </div>
      </div>
    );
  }

  renderContent (dapp) {
    const manifest = dapp.manifest || {};

    return (
      <div className={ styles.content }>
        <div>
          { this.renderInputs(dapp) }
        </div>

        <div className={ styles.code }>
          <div className={ styles.codeTitle }>manifest.json</div>
          <div className={ styles.codeContainer }>
            <code>{ JSON.stringify(manifest, null, 2) }</code>
          </div>
        </div>
      </div>
    );
  }

  renderHeader (dapp) {
    const { id, imageUrl } = dapp;
    const manifest = dapp.manifest || {};

    const infos = [];

    if (manifest.version) {
      infos.push(`v${manifest.version}`);
    }

    if (manifest.author) {
      infos.push(`by ${manifest.author}`);
    }

    return (
      <div className={ styles.header }>
        <div className={ styles.icon }>
          <img src={ imageUrl } />
        </div>
        <div>
          <div className={ styles.name }>
            { manifest.name || 'Unnamed' }
          </div>
          <div className={ styles.info }>
            { id }
          </div>
          <div className={ styles.info }>
            { infos.length > 0 ? infos.join(', ') : null }
          </div>
        </div>
      </div>
    );
  }

  renderInputs (app) {
    if (this.dappsStore.isNew) {
      return null;
    }

    return [
      this.renderHashInput(app, 'image', 'Image hash, as generated by Githubhint', true),
      this.renderHashInput(app, 'manifest', 'Manifest hash, as generated by Githubhint'),
      this.renderHashInput(app, 'content', 'Content hash, as generated by Githubhint')
    ];
  }

  renderOwnerSelect (app) {
    const overlayImage = (
      <img
        className={ styles.overlayImage }
        src={ api.util.createIdentityImg(this.dappsStore.currentAccount.address, 4) }
      />
    );

    return (
      <Input
        hint={ this.dappsStore.currentAccount.address }
        label='Owner, select the application owner and editor'
        overlay={ overlayImage }
      >
        <SelectAccount />
      </Input>
    );
  }

  renderOwnerStatic (app) {
    const overlayImage = (
      <img
        className={ styles.overlayImage }
        src={ api.util.createIdentityImg(app.owner, 4) }
      />
    );

    return (
      <Input
        hint={ app.owner }
        label='Owner, the application owner and editor'
        overlay={ overlayImage }
      >
        <input value={ app.ownerName } readOnly />
      </Input>
    );
  }

  renderHashInput (app, type, label, withImage = false) {
    const handleChange = (event) => {
      return this.handleChangeHash(event, type);
    };

    const hash = app[`${type}Hash`];

    const overlayImage = (withImage && hash)
      ? (
        <img
          className={ styles.overlayImage }
          src={ `/api/content/${hash.substr(2)}` }
        />
      )
      : null;

    const hint = app[`${type}Error`] || app[`${type}Hash`] || '...';
    const value = app[`${type}Url`] || '';

    return (
      <Input
        hint={ hint }
        label={ label }
        key={ `${type}Edit` }
        overlay={ overlayImage }
      >
        <input
          value={ value }
          data-dirty={ app[`${type}Changed`] }
          data-error={ !!app[`${type}Error`] }
          readOnly={ !this.dappsStore.isEditing && !this.dappsStore.isNew }
          onChange={ handleChange }
        />
      </Input>
    );
  }

  stopEvent = (event) => {
    event.stopPropagation();
    event.preventDefault();

    return false;
  }

  handleKeyPress = (event) => {
    const codeName = keycode(event);

    if (codeName === 'esc') {
      return this.handleClose();
    }

    return event;
  }

  handleCloseKeyPress = (event) => {
    const codeName = keycode(event);

    if (codeName === 'enter') {
      return this.handleClose();
    }

    return event;
  }

  handleOpen = () => {
    if (!this.refs.container) {
      return false;
    }

    // Focus after the modal is open
    setTimeout(() => {
      const element = ReactDOM.findDOMNode(this.refs.container);

      element && element.focus();
    }, 50);
  }

  handleClose = () => {
    this.props.onClose();
  }

  handleChangeHash  = (event, type) => {
    if (!this.dappsStore.isNew && !this.dappsStore.isEditing) {
      return;
    }

    const hash = event.target.value;
    let changed = false;
    let url = null;

    if (this.dappsStore.isNew) {
      if (hash && hash.length) {
        changed = true;
      }
    } else {
      if (this.dappsStore.currentApp[`${type}Hash`] !== hash) {
        changed = true;
      } else {
        url = this.dappsStore.currentApp[`${type}Url`];
      }
    }

    this.dappsStore.editWip({
      [`${type}Changed`]: changed,
      [`${type}Error`]: null,
      [`${type}Hash`]: hash,
      [`${type}Url`]: changed ? 'Resolving url from hash' : url
    });

    if (changed) {
      if (hash.length) {
        this.dappsStore
          .lookupHash(hash)
          .then((url) => {
            this.dappsStore.editWip({
              [`${type}Error`]: url ? null : 'Unable to resolve url',
              [`${type}Url`]: url
            });
          });
      } else {
        this.dappsStore.editWip({ [`${type}Url`]: null });
      }
    }
  }
}
